# docker/docker-compose.yml
version: "3.8"
services:
  pulsestudio:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: npm start